## build app image
# ./mvnw clean package spring-boot:build-image

## run MongoDB Docker image
# docker run --name mongo -d -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=example -p 27017:27017 mongo

## run app image
# docker run --name uppercasemongo -d -e UPPERCASEDB_MONGOHOST=mongo --link mongo:mongo -p 8080:8080 docker.io/library/spring6-reactive-mongodb-uppercaseband-webapp:0.0.1-SNAPSHOT

services:
  mongo:
    container_name: mongo
    image: mongo
    platform: linux/amd64
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    expose:
      - "27017"
    ports:
      - 27017:27017

  uppercasemongo:
    container_name: uppercasemongo
    image: docker.io/library/spring6-reactive-mongodb-uppercaseband-webapp:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - UPPERCASEDB_MONGOHOST=mongo
    depends_on:
      - mongo
